### ISSUE TITLE
Pipeline vs. conversion

### ISSUE THREAD

**Issue by balhoff** [NCI-Thesaurus/thesaurus-obo-edition#1]
Something to figure out early on: for the "OBO Library Edition" of NCIT, are we creating a pipeline which will be run each time NCIT is released, and create a separate OBO Library artifact, or are we converting NCIT to OBO conventions permanently?

**Comment by balhoff** [comment]
By "OBO conventions", I am thinking primarily of annotation properties used, term IRI structure, ontology IRI structure, etc.

**Comment by cmungall** [comment]
I think a pipeline at first, to allow us to compare side by side, then we'll see about various degrees of conversion at source
