### ISSUE TITLE
Neoplasm_Core.txt not found at EVS site

### ISSUE THREAD

**Issue by balhoff** [NCI-Thesaurus/thesaurus-obo-edition#17]
Hi @fragosog I built a new OBO Edition release but our neoplasm subset was empty. The makefile is downloading the neoplasm list from here:

https://evs.nci.nih.gov/ftp1/NCI_Thesaurus/Neoplasm/Neoplasm_Core.txt

(linked from [here](https://evs.nci.nih.gov/ftp1/NCI_Thesaurus/Neoplasm/About_Core.html))

Currently it's returning:

```
Not Found

The requested URL /ftp1/NCI_Thesaurus/Neoplasm/Neoplasm_Core.txt was not found on this server.
```

Is this a mistake?

Thanks!

**Comment by fragosog** [comment]
Woa!  I've fixed the filename (was missing the underscore) in the FTP site but I'll also tell the people generating the files.  Sorry about that, if you fire make again you should get the file now.

**Comment by balhoff** [comment]
Thanks!
