### ISSUE TITLE
Hemophagocytic Syndrome vs Hemophagocytic Lymphohistiocytosis

### ISSUE THREAD

**Issue by cmungall** [NCI-Thesaurus/thesaurus-obo-edition#19]
HLH is an only-child in NCIT:

```
 / NCIT:C7057 ! Disease, Disorder or Finding
  is_a NCIT:C2991 ! Disease or Disorder
   is_a NCIT:C28193 ! Syndrome
    is_a NCIT:C35439 ! Hemophagocytic Syndrome *** 
     is_a NCIT:C34792 ! Hemophagocytic Lymphohistiocytosis
      is_a NCIT:C121184 ! Secondary Hemophagocytic Lymphohistiocytosis
      is_a NCIT:C61276 ! Familial Hemophagocytic Lymphohistiocytosis
```

the def of HS mentions primary and secondary HLH but no non-HLH subtypes:

 * NCIT:C35439 ! Hemophagocytic Syndrome  [DEF: "A classification of rare, non-neoplastic, proliferative disorders of the hematologic system. Primary or familial hemophagocytic lymphohistiocytosis (HLH) is inherited with an autosomal recessive pattern with five known subtypes differentiated by specific genetic mutations. Secondary manifestation of HLH is usually seen in hyperactivated immunologic states such as infection, autoimmune disease or malignancy. Histiocytes in the bone marrow, spleen or lymph nodes become activated to the point that phagocytosis proceeds unchecked. Clinical signs usually present within the first decade and include fever, jaundice, hepatosplenomegaly, lymphadenopathy and skin rash. Prompt initiation of treatment improves survival though prognosis remains poor even with intervention."]

HLH:

 * NCIT:C34792 ! Hemophagocytic Lymphohistiocytosis [DEF: "A rare but potentially life-threatening disorder characterized by the proliferation of histiocytes and macrophages and phagocytosis of red blood cells, white blood cells, and platelets. It may be inherited or secondary, due to infections, autoimmune disorders, or underlying malignancies. Signs and symptoms include fever, lymphadenopathy, hepatomegaly, splenomegaly, and pancytopenia."]

Orphanet treats HLH and HS as the same thing.

Is the NCIT decision deliberate or should these be merged?

**Comment by NCIEVS** [comment]
Apparently this is deliberate.  From the editor in charge of this area:

"This question of hemophagocytic syndrome vs hemophagocytic lymphohistiocytosis has come up before. I would leave them as two separate entities. It is true that in the vast majority of cases these two terms are interchangeable but the term hemophagocytic syndrome may include rare cases which are not necessarily qualified as hemophagocytic lymphohistiocytosis."

**Comment by cmungall** [comment]
Thanks! I wonder if the Orphanet people would consider a consistent representation? cc @annieorly

closing this as I think there is no action for ncit here
