### ISSUE TITLE
Term identifier strategy

### ISSUE THREAD

**Issue by balhoff** [NCI-Thesaurus/thesaurus-obo-edition#2]
Will the NCIT OBO Library edition use standard PURLs like `http://purl.obolibrary.org/obo/NCIT_nnnnnnn`? This would differ from the IRIs currently in the ontology, which are like: `http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C2868`

Current IRIs end up pulling down the entire ontology when dereferenced. OBO PURLs would be able to dereference to individual term pages, e.g. at Ontobee (example from Uberon: http://purl.obolibrary.org/obo/UBERON_0001461).

OBO PURLs would still reference the existing NCIT code with the `code` annotation property.

**Comment by balhoff** [comment]
OBO PURLs could use generated numeric IDs, or instead simply prefix the NCIT code like `http://purl.obolibrary.org/obo/NCIT_C2868`. Either way the `code` annotation property can link to the basic code like `C2868`.

**Comment by cmungall** [comment]
How about starting with http://purl.obolibrary.org/obo/NCIT_C2868 as a strawman?

**Comment by mellybelly** [comment]
+1 @cmungall that would be my preference too

**Comment by balhoff** [comment]
We have a couple of competing proposals:

1. The OBO-standard way to do this would be the above proposed style: `http://purl.obolibrary.org/obo/NCIT_C2868`.
    * This form is conventional and meets expectations  of many OBO-centric tools for IRI compaction, where `http://purl.obolibrary.org/obo/NCIT_` is mapped to an `NCIT` prefix, creating `NCIT:C2868`.
    * It will also work well with the default term resolution configuration in the OBO PURL system. However this is configurable.

2. A slash-based format: `http://purl.obolibrary.org/obo/NCIt/C2868` (preferred by @fragosog)
    * This conforms to expectations of many semantic web tools to break on the final `/` or `#` to create a prefixed ID. Here, if `http://purl.obolibrary.org/obo/NCIt/` is mapped to an `NCIT` prefix, we would again have the prefixed ID `NCIT:C2868`.
    * Using this exact format would interfere with the typical OBO pattern of mapping paths under the ontology prefix to project-defined resources, e.g. `http://purl.obolibrary.org/obo/NCIT/releases/...`. This can be worked around (probably) by using the PURL config to first match all configured subpaths, and consider any unmatched paths to be a term. Alternatively, this form might be more convenient: `http://purl.obolibrary.org/obo/NCIt/terms/C2868`

From the perspective of standard semantic web tools, the choice doesn't really matter, since IRIs are the primary ID form, and a prefixed compact form is just a file-local construct (with prefix mapping defined within the file). However, since the goal of this project is increased compatibility with OBO Library ontologies and toolchain, I favor option 1, which supports OBO assumptions for compact IRI expansion when prefix mappings aren't provided.

**Comment by mellybelly** [comment]
I also favor choice 1 if possible but also understand if it cannot be made so. @jmcmurry will have an opinion too I am sure.

**Comment by jmcmurry** [comment]
+1 to option 1

**Comment by fragosog** [comment]
I kind of like 2 dot 2: ```http://purl.obolibrary.org/obo/NCIt/terms/C2868```.  But if the consensus is 1, let's go with that and see what problems come up on our side.  We could put an explanation in the owl:ontology/rdfs:comment.

**Comment by decorons** [comment]
I'm OK also with trying option 1.  We want it to work well with default term resolution in OBO communities.  As long as eventually, we have a way to say 'this is an alias of that'.  i.e. there will be two IRIs for the same concept floating around.

**Comment by balhoff** [comment]
It seems like we have a place to start with this, so I'll close the ticket. A version of the ontology with OBO-style IDs is linked in the [README](https://github.com/NCI-Thesaurus/thesaurus-obo-edition/blob/master/README.md).
