### ISSUE TITLE
Malformed URIs exist in neoplasm-core.owl 

### ISSUE THREAD

**Issue by yy20716** [NCI-Thesaurus/thesaurus-obo-edition#21]
I found that there are some curies which are not converted into URIs properly, e.g., there are no prefixes named as urn. Here is the result of grep over those URIs.

> yy20716@yy20716-Dell-Precision-M3800:~/eclipse-workspace$ grep "urn:swrl" neoplasm-core.owl -n
> 1005144:    <rdf:Description rdf:about="urn:swrl#y">
> 1005147:    <rdf:Description rdf:about="urn:swrl#x">
> 1005150:    <rdf:Description rdf:about="urn:swrl#z">
> 1005153:    <rdf:Description rdf:about="urn:swrl#B">
> 1005156:    <rdf:Description rdf:about="urn:swrl#C">
> 1005159:    <rdf:Description rdf:about="urn:swrl#A">
> 1005162:    <rdf:Description rdf:about="urn:swrl#D">
> 1005165:    <rdf:Description rdf:about="urn:swrl#mf">
> 1005168:    <rdf:Description rdf:about="urn:swrl#eff">
> 1005171:    <rdf:Description rdf:about="urn:swrl#in">
> 1005174:    <rdf:Description rdf:about="urn:swrl#mf2">
> ...

**Comment by balhoff** [comment]
These are the IRIs created by OWL API to stand for SWRL rule variables; they're not actually curies. But you are right, they're not correct syntax. The [spec for URN](https://tools.ietf.org/html/rfc2141) says:

```
<URN> ::= "urn:" <NID> ":" <NSS>
```

I'll file a bug with OWL API, because there's no reason these can't be something like `urn:swrl:C`. Are you using a tool that complained about these? Just curious because they hadn't caused a problem for me before.

**Comment by yy20716** [comment]
Oh I see. I found these IRIs while testing with DL-learner because its internal parser complains that those are malformed. These are not currently critical issues for using DL-learner for right now but I just wanted to report these issues so that other people would not see such messages.

**Comment by balhoff** [comment]
I opened an issue at https://github.com/owlcs/owlapi/issues/732

@yy20716 just curious, could you try changing all these from e.g. `urn:swrl#y` to `urn:swrl:y`? I would like to know if that makes DL-Learner happy.

**Comment by yy20716** [comment]
I am sorry - I completely forgot this issue due to other tasks I am doing right now. Yes, I just tried and confirmed that changing the IRIs works, i.e. error messages are not produced anymore. Thank you.

**Comment by balhoff** [comment]
Also, in case you didn't see, this was changed in OWL API. But it may be a while for this change to propagate to various ontologies.

**Comment by yy20716** [comment]
I see. I will try again with updated datasets later. Thank you for your kind explanation.
