### ISSUE TITLE
eyelid melanoma is indirectly asserted to be non-cutaneous

### ISSUE THREAD

**Issue by cmungall** [NCI-Thesaurus/thesaurus-obo-edition#22]
I have a question about this structure

 * [NCIT:C8711](http://purl.obolibrary.org/obo/NCIT_C8711) ! Non-Cutaneous Melanoma
      * [NCIT:C8562](http://purl.obolibrary.org/obo/NCIT_C8562) ! Ocular Melanoma  
          * [NCIT:C4358](http://purl.obolibrary.org/obo/NCIT_C4358) ! Eyelid Melanoma

eyelid melanoma has no named child classes, it's definition is:

_A melanoma that arises from the upper or lower eyelid_

AFAICT some if not most eyelid melanomas are cutaneous, e.g.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4869455

One way around this would be to redefine ocular melanoma to be restricted to melanomas of the eye*ball*. The combination of eye plus adnexa (current definition) seems to histologically heterogeneous to make strong assertions.

Note to self: this is the MONDO Protege explanation that lead to this:

![image](https://user-images.githubusercontent.com/50745/34923424-9e9ed2bc-f950-11e7-9340-2f344c19d76f.png)

**Comment by cmungall** [comment]
Another note mostly to self: ORDO classifies 'familial melanoma' as being part-of eyelid melanoma: https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_618 - we should excluded this when building mondo

**Comment by NCIEVS** [comment]
From the NCIt editing group:
"We moved ocular melanoma directly under melanoma and this resolves the conflict. The definition of ocular melanoma cannot be changed because it applies to both eye and adnexal lesions."

**Comment by cmungall** [comment]
Thanks, this makes sense
