### ISSUE TITLE
astrocytoma vs astrocytic tumor

### ISSUE THREAD

**Issue by cmungall** [NCI-Thesaurus/thesaurus-obo-edition#23]
NCIT appears to formally treat astrocytes and GBM as distinct, with an astrocytic tumor unifying them.

To the casual user of NCIT the difference of these may not be apparent. Many other resources - rightly or wrongly - use the term astrocyte as the parent class here

The definitions are very similar (identical in the core part, before the `.`):

 * _A glial tumor of the brain or spinal cord showing astrocytic differentiation.  It includes the following clinicopathological entities: pilocytic astrocytoma, diffuse astrocytoma, anaplastic astrocytoma, pleomorphic xanthoastrocytoma, subependymal giant cell astrocytoma, and glioblastoma_
 * _A tumor of the brain or spinal cord showing astrocytic differentiation. It includes the following clinicopathological entities: pilocytic astrocytoma, diffuse astrocytoma, anaplastic astrocytoma, pleomorphic xanthoastrocytoma, and subependymal giant cell astrocytoma._

Diffing the text we can see that the former includes glioblastoma

I suggest making the difference more obvious to avoid the casual user selecting 'astrocytoma' when they actually mean 'astrocytic tumor'. I'm not sure how best to do this. An rdfs:comment with a note here? In OBO we have properties such as 'editor note' and 'curator note' and in ontologies such as GO we also include comments for curators and users where the terminology can be ambiguous, to avoid annotation errors.

**Comment by cmungall** [comment]
As an example of what is possibly more colloquial usage, ORDO has:

![image](https://user-images.githubusercontent.com/50745/34957272-c0b5efc0-f9e1-11e7-99a8-76c7d1672dee.png)

The low-grade/high grade astrocytoma classification corresponds to LG/HG astrocytic tumor in NCIT

**Comment by NCIEVS** [comment]
The editing group has added a design note:

"Glioblastoma is not an astrocytoma. It is an astrocytic tumor. The latter includes astrocytomas and glioblastomas.  However, when an anaplastic astrocytoma progresses to grade IV tumor, it is called a glioblastoma."
