### ISSUE TITLE
Zellweger syndrome vs spectrum

### ISSUE THREAD

**Issue by cmungall** [NCI-Thesaurus/thesaurus-obo-edition#24]
I think there is a terminological issue here:

![img](https://user-images.githubusercontent.com/50745/35198645-75be0916-fea6-11e7-912c-efdd00e76777.png)

NCIT is using "Zellweger syndrome" to denote what I believe is more properly called "Zellweger spectrum". For a full analysis see this linked ticket:

https://github.com/monarch-initiative/mondo-build/issues/61

**Comment by cmungall** [comment]
An additional confounding issue is the (infantile) refsum issue. I believe the bare string "Refsum" disease typically refers to the adult form. In either case, it should be IRD (not the generic or adult form) that is placed under ZWS spectrum (see above point from spectrum vs ZWS itself)

**Comment by cmungall** [comment]
I think there are analogous concerns with the single-child adrenoleukodystrophy branch here.

Normally adrenoleukodystrophy refers to X-linked adrenoleukodystrophy. Neonatal adrenoleukodystrophy is autosomal. Furthermore it it is NALD that should be linked to the ZWS spectrum, not any hypothetical generic form...

**Comment by NCIEVS** [comment]
Here's the comment from the editing group:

"We have added a concept “Zellweger Spectrum Disorder” C146639, and have rearranged the hierarchy in the area of leukodystrophy. I hope that this will address all of the concerns raised on the thread."

**Comment by cmungall** [comment]
Wonderful, thank you!

**Comment by kanems** [comment]
Hi, I have a question regarding the name choice for this term: C146639. We are trying to resolve the various terms from UMLS, Mondo and all of their cross-referenced databases for the PBD/ZSS concepts. It appears that, conceptually, NCI C146639 is the same as SNOMED_CT (US) 742876007, see http://purl.bioontology.org/ontology/SNOMEDCT/742876007
Yet the preferred name from NCI suggests this concept is more narrow for "Zellweger" type-presentations.  Would NCI consider renaming or maybe reporting that the concept is synonymous to the SNOMED term above (if it is true these concepts are equivalent)?
