### ISSUE TITLE
kidney, ureter and renal pelvis in NCIT

### ISSUE THREAD

**Issue by cmungall** [NCI-Thesaurus/thesaurus-obo-edition#43]
My understanding is that

 * 'kidney + ureter' = the collective structure of the kidneys plus ureter (thus includes all kidney parts, eg nephrons)
 * 'renal pelvis + ureter' = the collective structure of the renal pelvis plus ureter (excludes structures like nephrons)

However, when we look at K+U: http://purl.obolibrary.org/obo/NCIT_C61107

we see it only has one part, RP+U. Single-parts are usually a bad sign..

I would expect the kidney to be a part of K+U

Here is the graph:

![image](https://user-images.githubusercontent.com/50745/47886896-f6ae1880-ddf9-11e8-8f84-cdfd53ad5692.png)

**Comment by NCIEVS** [comment]
From the editor in charge:

[I] made "kidney" : "physical part_of kidney and ureter". Since "kidney and ureter" is already "part_of urinary system", and in order to preserve the part_of logical structure, I removed the existing relationship "kidney": "part_of urinary system".
