### ISSUE TITLE
Age Group

### ISSUE THREAD

**Issue by ddooley** [NCI-Thesaurus/thesaurus-obo-edition#53]
The "Age Group" class (http://purl.obolibrary.org/obo/NCIT_C20587) is problematic in that its definition corresponds to a subclass of [population of organisms](http://purl.obolibrary.org/obo/PCO_0000001), but its subclasses "Youth", "Elderly" etc. are defined as referencing single people, not sets of people. Can we relocate the subclasses under "Person", extend their labels a bit, e.g. "Elderly Person", and create new subclasses of Age Group called "Youth Age Group", "Elderly Age Group" etc.?

**Comment by NCIEVS** [comment]
The textual definitions have been changed in the baseline NCIt.  They should be available in the next export at the end of September.  From the editor:

"I have uniformly revised the definitions to reflect that the intent of these concepts is to represent an age group."

**Comment by ddooley** [comment]
Ok, thanks.  Now are you folks interested in having individual person classes for the above, e.g. "Elderly Person".  My only reason is that I have a need for these convenience classes to populate a menu of epidemiological contact event person - listing off the type of person a patient came in contact with, which includes spouse, family member, caregiver, but also "child".  Just curious...

d.

**Comment by lmspterryquinn** [comment]
I have created Child Individual (C164216) as a child of Individual by Age Group which is a child of Person. There is an NCIt SY of Child.

**Comment by ddooley** [comment]
Ok thanks! I may have a few more person types to add as time goes on.
