### ISSUE TITLE
contact Ontobee about NCIT resolution

### ISSUE THREAD

**Issue by mellybelly** [NCI-Thesaurus/thesaurus-obo-edition#6]
We need to understand where current NCIT is coming from, and also if we can potentially resolve two files while we have our draft release in preparation (or perhaps indefinitely).

**Comment by decorons** [comment]
We have some info from Oliver He, and invitation to set up a meeting.

**Comment by balhoff** [comment]
This is resolved. The OBO Edition NCIT is on Ontobee.
