### ISSUE TITLE
Typo in C95745

### ISSUE THREAD

**Issue by rachhuntley** [NCI-Thesaurus/thesaurus-obo-edition#61]
Label should read 'Helplessness'
http://purl.obolibrary.org/obo/NCIT_C95745

Thanks,
Rachael.

**Comment by balhoff** [comment]
It looks like this has been fixed in the regular NCIt release; OBO edition is running behind. I will build a new version today.

**Comment by rachhuntley** [comment]
Thank you!

**Comment by balhoff** [comment]
This is updated now. It make take a few days to show up in Ontobee or OLS.
