### ISSUE TITLE
merge? NCIT:C35092 Attention Deficit Disorder and NCIT:C97160 Attention Deficit Hyperactivity Disorder

### ISSUE THREAD

**Issue by nicolevasilevsky** [NCI-Thesaurus/thesaurus-obo-edition#62]
NCIT:C35092 Attention Deficit Disorder and NCIT:C97160 Attention Deficit Hyperactivity Disorder

Should these two terms be merged?

From wikipedia: The condition was officially known as attention deficit disorder (ADD) from 1980 to 1987, while before this it was known as hyperkinetic reaction of childhood.  (https://en.wikipedia.org/wiki/Attention_deficit_hyperactivity_disorder)

If they are not to be merged, do you think they should be siblings, rather than parent and child? If they are siblings, what is the preferred parent?

Related ticket: https://github.com/monarch-initiative/mondo/issues/1930#issuecomment-687252776

**Comment by cmungall** [comment]
What's the status of this?

**Comment by nicolevasilevsky** [comment]
This has been addressed, see monarch-initiative/mondo#1930 (comment)

This ticket can be closed.
