### ISSUE TITLE
License clarification?

### ISSUE THREAD

**Issue by allaway** [NCI-Thesaurus/thesaurus-obo-edition#74]
Hello, 

I'm curious what license the NCIt is released under. We use (predominantly) the OBO edition of the NCIt. The [NCIt docs ](https://wiki.nci.nih.gov/display/EVS/NCI+Thesaurus+versus+NCI+Metathesaurus) state that it is available under an `Open content license`, while the [obofoundry](http://www.obofoundry.org/ontology/ncit.html) states that it is `CC-BY-4.0`. I just wanted to confirm that `CC-BY-4.0` is the appropriate license for us to reference when using the OBO-edition NCIt.

Thank you!

**Comment by allaway** [comment]
Ah, thanks so much for the quick reply and information!

In case it's helpful, I also saw the reference to the open content license here: https://evs.nci.nih.gov/support

Cheers,
Robert

**Comment by NCIEVS** [comment]
Ah!  Thanks for that catch!

cheers,
Gilberto
