### ISSUE TITLE
Latest NCIt release?

### ISSUE THREAD

**Issue by janelomax** [NCI-Thesaurus/thesaurus-obo-edition#77]
The latest NCIt release on their website is 22.03d 2022-03-28 - looks like the OBO version hasn't been generated since Aug 2021.

Do you know when the next OBO update will be?

**Comment by balhoff** [comment]
Sorry, the pipeline was stuck. I've published a more recent update, and am running the current one now. I'll let you know when it is out.

**Comment by balhoff** [comment]
Updated now.
