### ISSUE TITLE
make Oncotree slim

### ISSUE THREAD

**Issue by mellybelly** [NCI-Thesaurus/thesaurus-obo-edition#8]
Oncotree seems to already be mapped to NCIT. It should be trivial to convert this file to RDF, add oncotree subset tags to these terms in our release, and then release an oncotree slim that uses the NCIT identifiers natively.

The file I found was in their API, not sure if there are other files elsewhere:
http://www.cbioportal.org/oncotree/swagger-ui.html

See also:
https://github.com/cBioPortal/oncotree
https://github.com/cBioPortal/oncotree-mapping

**Comment by balhoff** [comment]
The subset tags for `oncotree_slim` are now part of the ontology. @cmungall what is the best approach for extracting an ontology composed of just those terms, or just those and their superclasses? I tried this:

`owltools ncit.owl  --extract-subset oncotree_slim -o oncotree.owl`

That almost does the job but leaves in all the non-oncotree terms without annotations or axioms. I.e. the result has only 957 subclass axioms (about what I expect) but 128000 declared classes with no labels.

**Comment by cmungall** [comment]
You can always post-process with `--remove-dangling`

**Comment by balhoff** [comment]
Thanks, that is working.

**Comment by balhoff** [comment]
@mellybelly want to take a look?

http://purl.obolibrary.org/obo/ncit/ncit-oncotree.ttl

The Oncotree terms are there, but not grouped the way they are in OncoTree. The "tree" is according to some axis that won't be readily apparent via NCIt axioms. We should talk about whether/how to better represent this.

**Comment by balhoff** [comment]
Current version is somewhat better, but difficult to simplify to the level of OncoTree.
