### ISSUE TITLE
NCIT OBO has 5034 unsatisfiable classes

### ISSUE THREAD

**Issue by dillerm** [NCI-Thesaurus/thesaurus-obo-edition#84]
I used ROBOT to run the HermiT reasoner on this ontology and it identified the classes in the attached document as being unsatisfiable. Oddly, I couldn't find a contradiction in the axioms in the first one that I reviewed, which was 'MIR93' (C92467).

[unsatisfiable_classes_ncit_obo.xlsx](https://github.com/NCI-Thesaurus/thesaurus-obo-edition/files/9993528/unsatisfiable_classes_ncit_obo.xlsx)

**Comment by matentzn** [comment]
I just did the same thing, and I did not find any unsats:

```
wget http://purl.obolibrary.org/obo/ncit.owl
robot explain -i ncit.owl --reasoner hermit -M unsatisfiability --unsatisfiable random:20 --explanation unsat.md
```

Which version of ROBOT are you using? Which version of NCIT? Can you share the command?

**Comment by dillerm** [comment]
My ROBOT version is 1.8.2. I'm ran this on the NCIT-OBO release version 21.07d, which has a release date of 8/20/21. The command:

`robot reason --reasoner hermit --input ./data/input/ncit-obo.owl --output ./data/output/reasoned_ontologies/ncit-obo-reasoned.owl`

**Comment by matentzn** [comment]
Can you try the latest version [2022-08-19](https://github.com/NCI-Thesaurus/thesaurus-obo-edition/tree/v2022-08-19) and see if this is still true there?

**Comment by dillerm** [comment]
I updated my copy of ROBOT to 1.9.1 and re-ran it on the newest version, and everything looks good! Sorry for the false alarm!

**Comment by matentzn** [comment]
NP! :) Thanks for reaching out!
