### ISSUE TITLE
More updates?

### ISSUE THREAD

**Issue by janelomax** [NCI-Thesaurus/thesaurus-obo-edition#85]
Hi - are there plans to do any more updates on this version? Or is it superseded by the BioPortal version: https://bioportal.bioontology.org/ontologies/NCIT/

thanks

**Comment by matentzn** [comment]
I will make a new release later this week! Not superseded!

**Comment by matentzn** [comment]
Done: https://github.com/NCI-Thesaurus/thesaurus-obo-edition/releases/tag/v2023-10-19
